# Generated by Django 5.2.12 on 2026-03-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='statement_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='transactions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='loan',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='repaid_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='repayment_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
