# Generated by Django 5.2.12 on 2026-04-05 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_creditcard_statement_history_creditcard_transactions_and_more'),
        ('banking', '0002_update_field_visit_statuses'),
    ]

    operations = [
    ]
